# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: baidu_rpc_meta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import options_pb2 as options__pb2
import streaming_rpc_meta_pb2 as streaming__rpc__meta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='baidu_rpc_meta.proto',
  package='brpc.policy',
  syntax='proto2',
  serialized_options=_b('\n\017com.brpc.policyB\rBaiduRpcProto'),
  serialized_pb=_b('\n\x14\x62\x61idu_rpc_meta.proto\x12\x0b\x62rpc.policy\x1a\roptions.proto\x1a\x18streaming_rpc_meta.proto\"\xa0\x02\n\x07RpcMeta\x12,\n\x07request\x18\x01 \x01(\x0b\x32\x1b.brpc.policy.RpcRequestMeta\x12.\n\x08response\x18\x02 \x01(\x0b\x32\x1c.brpc.policy.RpcResponseMeta\x12\x15\n\rcompress_type\x18\x03 \x01(\x05\x12\x16\n\x0e\x63orrelation_id\x18\x04 \x01(\x03\x12\x17\n\x0f\x61ttachment_size\x18\x05 \x01(\x05\x12#\n\nchunk_info\x18\x06 \x01(\x0b\x32\x0f.brpc.ChunkInfo\x12\x1b\n\x13\x61uthentication_data\x18\x07 \x01(\x0c\x12-\n\x0fstream_settings\x18\x08 \x01(\x0b\x32\x14.brpc.StreamSettings\"\x86\x01\n\x0eRpcRequestMeta\x12\x14\n\x0cservice_name\x18\x01 \x02(\t\x12\x13\n\x0bmethod_name\x18\x02 \x02(\t\x12\x0e\n\x06log_id\x18\x03 \x01(\x03\x12\x10\n\x08trace_id\x18\x04 \x01(\x03\x12\x0f\n\x07span_id\x18\x05 \x01(\x03\x12\x16\n\x0eparent_span_id\x18\x06 \x01(\x03\"9\n\x0fRpcResponseMeta\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x12\n\nerror_text\x18\x02 \x01(\tB \n\x0f\x63om.brpc.policyB\rBaiduRpcProto')
  ,
  dependencies=[options__pb2.DESCRIPTOR,streaming__rpc__meta__pb2.DESCRIPTOR,])




_RPCMETA = _descriptor.Descriptor(
  name='RpcMeta',
  full_name='brpc.policy.RpcMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='brpc.policy.RpcMeta.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='brpc.policy.RpcMeta.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compress_type', full_name='brpc.policy.RpcMeta.compress_type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='correlation_id', full_name='brpc.policy.RpcMeta.correlation_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attachment_size', full_name='brpc.policy.RpcMeta.attachment_size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunk_info', full_name='brpc.policy.RpcMeta.chunk_info', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authentication_data', full_name='brpc.policy.RpcMeta.authentication_data', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream_settings', full_name='brpc.policy.RpcMeta.stream_settings', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=367,
)


_RPCREQUESTMETA = _descriptor.Descriptor(
  name='RpcRequestMeta',
  full_name='brpc.policy.RpcRequestMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='brpc.policy.RpcRequestMeta.service_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method_name', full_name='brpc.policy.RpcRequestMeta.method_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_id', full_name='brpc.policy.RpcRequestMeta.log_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trace_id', full_name='brpc.policy.RpcRequestMeta.trace_id', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='span_id', full_name='brpc.policy.RpcRequestMeta.span_id', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_span_id', full_name='brpc.policy.RpcRequestMeta.parent_span_id', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=504,
)


_RPCRESPONSEMETA = _descriptor.Descriptor(
  name='RpcResponseMeta',
  full_name='brpc.policy.RpcResponseMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='brpc.policy.RpcResponseMeta.error_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_text', full_name='brpc.policy.RpcResponseMeta.error_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=563,
)

_RPCMETA.fields_by_name['request'].message_type = _RPCREQUESTMETA
_RPCMETA.fields_by_name['response'].message_type = _RPCRESPONSEMETA
_RPCMETA.fields_by_name['chunk_info'].message_type = options__pb2._CHUNKINFO
_RPCMETA.fields_by_name['stream_settings'].message_type = streaming__rpc__meta__pb2._STREAMSETTINGS
DESCRIPTOR.message_types_by_name['RpcMeta'] = _RPCMETA
DESCRIPTOR.message_types_by_name['RpcRequestMeta'] = _RPCREQUESTMETA
DESCRIPTOR.message_types_by_name['RpcResponseMeta'] = _RPCRESPONSEMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RpcMeta = _reflection.GeneratedProtocolMessageType('RpcMeta', (_message.Message,), {
  'DESCRIPTOR' : _RPCMETA,
  '__module__' : 'baidu_rpc_meta_pb2'
  # @@protoc_insertion_point(class_scope:brpc.policy.RpcMeta)
  })
_sym_db.RegisterMessage(RpcMeta)

RpcRequestMeta = _reflection.GeneratedProtocolMessageType('RpcRequestMeta', (_message.Message,), {
  'DESCRIPTOR' : _RPCREQUESTMETA,
  '__module__' : 'baidu_rpc_meta_pb2'
  # @@protoc_insertion_point(class_scope:brpc.policy.RpcRequestMeta)
  })
_sym_db.RegisterMessage(RpcRequestMeta)

RpcResponseMeta = _reflection.GeneratedProtocolMessageType('RpcResponseMeta', (_message.Message,), {
  'DESCRIPTOR' : _RPCRESPONSEMETA,
  '__module__' : 'baidu_rpc_meta_pb2'
  # @@protoc_insertion_point(class_scope:brpc.policy.RpcResponseMeta)
  })
_sym_db.RegisterMessage(RpcResponseMeta)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
