# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming_rpc_meta.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import options_pb2 as options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='streaming_rpc_meta.proto',
  package='brpc',
  syntax='proto2',
  serialized_options=_b('\n\010com.brpcB\021StreamingRpcProto'),
  serialized_pb=_b('\n\x18streaming_rpc_meta.proto\x12\x04\x62rpc\x1a\roptions.proto\"Z\n\x0eStreamSettings\x12\x11\n\tstream_id\x18\x01 \x02(\x03\x12\x1c\n\rneed_feedback\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08writable\x18\x03 \x01(\x08:\x05\x66\x61lse\"\x9f\x01\n\x0fStreamFrameMeta\x12\x11\n\tstream_id\x18\x01 \x02(\x03\x12\x18\n\x10source_stream_id\x18\x02 \x01(\x03\x12#\n\nframe_type\x18\x03 \x01(\x0e\x32\x0f.brpc.FrameType\x12\x18\n\x10has_continuation\x18\x04 \x01(\x08\x12 \n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x05 \x01(\x0b\x32\x0e.brpc.Feedback\"!\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x15\n\rconsumed_size\x18\x01 \x01(\x03*{\n\tFrameType\x12\x16\n\x12\x46RAME_TYPE_UNKNOWN\x10\x00\x12\x12\n\x0e\x46RAME_TYPE_RST\x10\x01\x12\x14\n\x10\x46RAME_TYPE_CLOSE\x10\x02\x12\x13\n\x0f\x46RAME_TYPE_DATA\x10\x03\x12\x17\n\x13\x46RAME_TYPE_FEEDBACK\x10\x04\x42\x1d\n\x08\x63om.brpcB\x11StreamingRpcProto')
  ,
  dependencies=[options__pb2.DESCRIPTOR,])

_FRAMETYPE = _descriptor.EnumDescriptor(
  name='FrameType',
  full_name='brpc.FrameType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FRAME_TYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRAME_TYPE_RST', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRAME_TYPE_CLOSE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRAME_TYPE_DATA', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRAME_TYPE_FEEDBACK', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=338,
  serialized_end=461,
)
_sym_db.RegisterEnumDescriptor(_FRAMETYPE)

FrameType = enum_type_wrapper.EnumTypeWrapper(_FRAMETYPE)
FRAME_TYPE_UNKNOWN = 0
FRAME_TYPE_RST = 1
FRAME_TYPE_CLOSE = 2
FRAME_TYPE_DATA = 3
FRAME_TYPE_FEEDBACK = 4



_STREAMSETTINGS = _descriptor.Descriptor(
  name='StreamSettings',
  full_name='brpc.StreamSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='brpc.StreamSettings.stream_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_feedback', full_name='brpc.StreamSettings.need_feedback', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='writable', full_name='brpc.StreamSettings.writable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=139,
)


_STREAMFRAMEMETA = _descriptor.Descriptor(
  name='StreamFrameMeta',
  full_name='brpc.StreamFrameMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='brpc.StreamFrameMeta.stream_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_stream_id', full_name='brpc.StreamFrameMeta.source_stream_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='frame_type', full_name='brpc.StreamFrameMeta.frame_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_continuation', full_name='brpc.StreamFrameMeta.has_continuation', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feedback', full_name='brpc.StreamFrameMeta.feedback', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=301,
)


_FEEDBACK = _descriptor.Descriptor(
  name='Feedback',
  full_name='brpc.Feedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consumed_size', full_name='brpc.Feedback.consumed_size', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=336,
)

_STREAMFRAMEMETA.fields_by_name['frame_type'].enum_type = _FRAMETYPE
_STREAMFRAMEMETA.fields_by_name['feedback'].message_type = _FEEDBACK
DESCRIPTOR.message_types_by_name['StreamSettings'] = _STREAMSETTINGS
DESCRIPTOR.message_types_by_name['StreamFrameMeta'] = _STREAMFRAMEMETA
DESCRIPTOR.message_types_by_name['Feedback'] = _FEEDBACK
DESCRIPTOR.enum_types_by_name['FrameType'] = _FRAMETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamSettings = _reflection.GeneratedProtocolMessageType('StreamSettings', (_message.Message,), {
  'DESCRIPTOR' : _STREAMSETTINGS,
  '__module__' : 'streaming_rpc_meta_pb2'
  # @@protoc_insertion_point(class_scope:brpc.StreamSettings)
  })
_sym_db.RegisterMessage(StreamSettings)

StreamFrameMeta = _reflection.GeneratedProtocolMessageType('StreamFrameMeta', (_message.Message,), {
  'DESCRIPTOR' : _STREAMFRAMEMETA,
  '__module__' : 'streaming_rpc_meta_pb2'
  # @@protoc_insertion_point(class_scope:brpc.StreamFrameMeta)
  })
_sym_db.RegisterMessage(StreamFrameMeta)

Feedback = _reflection.GeneratedProtocolMessageType('Feedback', (_message.Message,), {
  'DESCRIPTOR' : _FEEDBACK,
  '__module__' : 'streaming_rpc_meta_pb2'
  # @@protoc_insertion_point(class_scope:brpc.Feedback)
  })
_sym_db.RegisterMessage(Feedback)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
